## 此為範例
## 建立 K8S 的 service
apiVersion: v1
kind: Service
metadata:
  name: whoami-service
  namespace: default
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: whoami
---
## 建立 K8S 的 deployment
## 如果需要 autoscale 功能，請參考：https://kubernetes.io/zh/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: whoami
  name: whoami-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
        - image: containous/whoami:latest
          name: whoami
          ports:
            - containerPort: 80
              name: web
