name: Test Github Action Demo
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      ## checkout code
      - uses: actions/checkout@v2
      ## define golang version
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.1'
      ## print go version
      - run: go version
      ## install package (kubectl / awscli) on ubuntu
      - run: |
          curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
          echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
          apt-get update
          apt-get install -y kubectl awscli
      ## run build
      - run: |
          go get -u github.com/swaggo/swag/cmd/swag
          swag init
          go build -o mypro main.go
        id: build_result
      ## 登入 docker hub
#      - uses: docker/login-action@v1
#        name: Login to docker hub
#        with:
          # @TODO：需要在 github Settings > Secrets > New Repository Secret 建立 DOCKER_USERNAME / DOCKER_PASSWORD 並填入 docker hub 帳密
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
      ## 開始編譯成 docker image 並推送至 docker hub 上
      - uses: docker/build-push-action@v2
        name: Push to docker hub
        with:
          push: true
          # @TODO：需要開一個 docker hub repo 放 image，並填入到這裡
          tags: my/image:latest
      ## image 推送後還不會反映到服務上
      ## 必須透過以下方式才能正確反映變更的效果：
      ## 1. kubectl rollout restart deployment [deployment_name]
      ## 2. 進 ArgoCD 手動 restart deployment
      ## 3. 使用 ArgoCD Image Updater @TODO：正在測試
