name: Test Github Action Demo
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      ## checkout code
      - uses: actions/checkout@v2
      ## define golang version
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.1'
      ## print go version
      - run: go version
      ## run build
      - run: go build -o mypro main.go
        id: build_result
      - run: docker build -t preview:latest .
        id: docker_build_result
